import { Karla } from "next/font/google";
import "./globals.css";

const karla = Karla({
  subsets: ['latin'],
  variable: "--font-karla",
  weight: ['400','700'],
});

export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${karla.variable} antialiased`}>{children}</body>
    </html>
  );
}
