export const CardMenu = [
  {
    id: 1,
    title: "Waffle",
    subTitle: "Waffle with Berries",
    price: 6.50,
    imgDesktop: "/images/image-waffle-desktop.jpg",
    imgTablet: "/images/image-waffle-tablet.jpg",
    imgMobile: "/images/image-waffle-mobile.jpg",
  },
  {
    id: 2,
    title: "Crème Brûlée",
    subTitle: "Vanilla Bean Crème Brûlée",
    price: 7.00,
    imgDesktop: "/images/image-creme-brulee-desktop.jpg",
    imgTablet: "/images/image-creme-brulee-tablet.jpg",
    imgMobile: "/images/image-creme-brulee-mobile.jpg",
  },
  {
    id: 3,
    title: "Macaron",
    subTitle: "Macaron Mix of Five",
    price: 8.00,
    imgDesktop: "/images/image-macaron-desktop.jpg",
    imgTablet: "/images/image-macaron-tablet.jpg",
    imgMobile: "/images/image-macaron-mobile.jpg",
  },
  {
    id: 4,
    title: "Tiramisu",
    subTitle: "Classic Tiramisu",
    price: 5.50,
    imgDesktop: "/images/image-tiramisu-desktop.jpg",
    imgTablet: "/images/image-tiramisu-tablet.jpg",
    imgMobile: "/images/image-tiramisu-mobile.jpg",
  },
  {
    id: 5,
    title: "Baklava",
    subTitle: "Pistachio Baklava",
    price: 4.00,
    imgDesktop: "/images/image-baklava-desktop.jpg",
    imgTablet: "/images/image-baklava-tablet.jpg",
    imgMobile: "/images/image-baklava-mobile.jpg",
  },
  {
    id: 6,
    title: "Pie",
    subTitle: "Lemon Meringue Pie",
    price: 5.00,
    imgDesktop: "/images/image-meringue-desktop.jpg",
    imgTablet: "/images/image-meringue-tablet.jpg",
    imgMobile: "/images/image-meringue-mobile.jpg",
  },
  {
    id: 7,
    title: "Cake",
    subTitle: "Red Velvet Cake",
    price: 4.50,
    imgDesktop: "/images/image-cake-desktop.jpg",
    imgTablet: "/images/image-cake-tablet.jpg",
    imgMobile: "/images/image-cake-mobile.jpg",
  },
  {
    id: 8,
    title: "Brownie",
    subTitle: "Salted Caramel Brownie",
    price: 5.50,
    imgDesktop: "/images/image-brownie-desktop.jpg",
    imgTablet: "/images/image-brownie-tablet.jpg",
    imgMobile: "/images/image-brownie-mobile.jpg",
  },
  {
    id: 9,
    title: "Panna Cotta",
    subTitle: "Vanilla Panna Cotta",
    price: 6.50,
    imgDesktop: "/images/image-panna-cotta-desktop.jpg",
    imgTablet: "/images/image-panna-cotta-tablet.jpg",
    imgMobile: "/images/image-panna-cotta-mobile.jpg",
  },
];
